name: PermGuard
version: '${project.version}'
main: com.roboter5123.permguard.PermGuard
api-version: '1.20'
depend: [LuckPerms]
permissions:
  permguard.join:
    description: "Permission to join this Server"
dependencies:
  server:
    LuckPerms:
      load: BEFORE
      required: true
      join-classpath: true